[general]
flip_aug = true
color_aug = false
shuffle_caption = false
caption_tag_dropout_rate = 0.0
caption_extension = ".txt"

[[datasets]]
batch_size = 4
enable_bucket = true
resolution = 512
min_bucket_reso = 256
max_bucket_reso = 768
bucket_reso_steps = 64

  [[datasets.subsets]]
  image_dir = "/data/xander/Projects/cog/xander_eden_stuff/clipxdata/clipx_dataset"
  num_repeats = 1